spring:
  application:
    name: Job_Backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: http://123.57.153.74:6379/Job?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 123.57.153.74
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      password: yes
  kafka:
    bootstrap-servers: 123.57.153.74:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: Job_Back
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
    listener:
      missing-topics-fatal: true
#  mail:
#    host: smtp.qq.com
#    username: zpddd777@qq.com
#    password: rtqymxjhzbshbeec
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid



logging:
  level:
    root: info

