spring:
  profiles:
    active: dev
  application:
    name: Job_Backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: http://123.57.153.74:6379/Job?serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: 123.57.153.74
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  kafka:
    bootstrap-servers: 123.57.153.74:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: Job_Back
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 100
    listener:
      missing-topics-fatal: true

  servlet:
    multipart:
      enabled: true
      location: src/main/resources/static
      max-file-size: 100MB
  mvc:
    static-path-pattern: src/main/resources/static
  web:
    resources:
      static-locations: src/main/resources/static
#  mail:
#    host: smtp.qq.com
#    username: zpddd777@qq.com
#    password: rtqymxjhzbshbeec
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid

file:
  upload-dir: src/main/resources/static/

logging:
  level:
    root: info

