spring:
  application:
    name: Job_Backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.187.230:3306/xiao
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 123.57.153.74
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      password: "mty030806"
  kafka:
    bootstrap-servers: 123.57.153.74:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "buaa.cxtj.job_backend.POJO.Entity"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: Job_Back
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 100
      properties:
        spring:
          json:
            trusted:
              packages: "buaa.cxtj.job_backend.POJO.Entity"
    listener:
      missing-topics-fatal: true

  servlet:
    multipart:
      enabled: true
      location: src/main/resources/static
      max-file-size: 100MB
  mvc:
    static-path-pattern: src/main/resources/static
  web:
    resources:
      static-locations: src/main/resources/static
#  mail:
#    host: smtp.qq.com
#    username: zpddd777@qq.com
#    password: rtqymxjhzbshbeec
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

file:
  upload-dir: src/main/resources/static/

openai:
  api-key: sk-lKY42a3cbe311b0c84e7481d51e8512278df461306ebUrW4


logging:
  level:
    root: info

