version: '1.0'
name: pipeline-auto
displayName: pipeline-auto
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - dev
stages:
  - name: build
    displayName: deploy
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID:
          ID: '1'
          hostID:
            - 038364de-1ec4-44fe-936d-bf910d8c7d85
        script:
          - cd ~/Job_Backend
          - ./deploy.sh
        notify: []
        strategy:
          retry: '0'
