version: '1.0'
name: pipeline-auto
displayName: pipeline-auto
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - dev
stages:
  - name: build
    displayName: deploy
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID:
          ID: '1'
          hostID:
            - cd2dccc0-e4fc-4e87-9fd2-9aed81b4e264
        script:
          - cd ~/mty/Job_Backend
          - ./deploy.sh
        notify: []
        strategy:
          retry: '0'
